version: "2.2"
services:
  fastapi_template:
    build:
      context: .
      dockerfile: docker/base/Dockerfile
    command: python3 fastapi_template.py
    ports:
      - "8010:8010"
    volumes:
      - .:/code
    links:
      - redis
      - db
      - dbmate
      - mailhog
    depends_on:
      redis:
        condition: service_started
      mailhog:
        condition: service_started
      db:
        condition: service_healthy

    environment:
      - SRVC_CONFIG=etc/local.json

  redis:
    image: redis

  db:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=fastapi_template
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  dbmate:
    image: amacneil/dbmate
    command: -d "/code/etc/db/migrations" up
    volumes:
      - .:/code
    links:
      - db
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/fastapi_template?sslmode=disable

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
