--migrate:up


CREATE TABLE goods (
    id SERIAL PRIMARY KEY,
    en BOOLEAN DEFAULT TRUE,
    name VARCHAR(100),
    description VARCHAR(250),
    ctime TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (NOW() at time zone 'utc'),
    atime TIMESTAMP WITHOUT TIME ZONE DEFAULT NULL,
    dtime TIMESTAMP WITHOUT TIME ZONE DEFAULT NULL
);



--migrate:down


DROP TABLE goods CASCADE;